In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LogisticRegression

In [6]:
#Read the data set
data=pd.read_csv("bank-full.csv",sep=';')
data.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

# EDA

In [7]:
data.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [9]:
data.isna().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [10]:
data.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [15]:
data.shape

(45211, 17)

In [40]:
data["contact"].value_counts()

cellular     29285
unknown      13020
telephone     2906
Name: contact, dtype: int64

In [23]:
data["housing"].value_counts()

yes    25130
no     20081
Name: housing, dtype: int64

In [24]:
data["loan"].value_counts()

no     37967
yes     7244
Name: loan, dtype: int64

In [42]:
bank1=pd.get_dummies(data,columns=['job','marital','education','contact','poutcome'])
bank1

age default  balance housing loan  day month  duration  campaign  \
0       58      no     2143     yes   no    5   may       261         1   
1       44      no       29     yes   no    5   may       151         1   
2       33      no        2     yes  yes    5   may        76         1   
3       47      no     1506     yes   no    5   may        92         1   
4       33      no        1      no   no    5   may       198         1   
...    ...     ...      ...     ...  ...  ...   ...       ...       ...   
45206   51      no      825      no   no   17   nov       977         3   
45207   71      no     1729      no   no   17   nov       456         2   
45208   72      no     5715      no   no   17   nov      1127         5   
45209   57      no      668      no   no   17   nov       508         4   
45210   37      no     2971      no   no   17   nov       361         2   

       pdays  ...  education_secondary education_tertiary  education_unknown  \
0         -1  ...                    0                  1                  0   
1         -1  ...                    1                  0                  0   
2         -1  ...                    1                  0                  0   
3         -1  ...                    0                  0                  1   
4         -1  ...                    0                  0                  1   
...      ...  ...                  ...                ...                ...   
45206     -1  ...                    0                  1                  0   
45207     -1  ...                    0                  0                  0   
45208    184  ...                    1                  0                  0   
45209     -1  ...                    1                  0                  0   
45210    188  ...                    1                  0                  0   

       contact_cellular  contact_telephone  contact_unknown  poutcome_failure  \
0                     0                  0                1                 0   
1                     0                  0                1                 0   
2                     0                  0                1                 0   
3                     0                  0                1                 0   
4                     0                  0                1                 0   
...                 ...                ...              ...               ...   
45206                 1                  0                0                 0   
45207                 1                  0                0                 0   
45208                 1                  0                0                 0   
45209                 0                  1                0                 0   
45210                 1                  0                0                 0   

       poutcome_other  poutcome_success  poutcome_unknown  
0                   0                 0                 1  
1                   0                 0                 1  
2                   0                 0                 1  
3                   0                 0                 1  
4                   0                 0                 1  
...               ...               ...               ...  
45206               0                 0                 1  
45207               0                 0                 1  
45208               0                 1                 0  
45209               0                 0                 1  
45210               1                 0                 0  

[45211 rows x 38 columns]

In [43]:
bank1['default'] = np.where(bank1['default'].str.contains("yes"), 1, 0)
bank1['housing'] = np.where(bank1['housing'].str.contains("yes"), 1, 0)
bank1['loan'] = np.where(bank1['loan'].str.contains("yes"), 1, 0)
bank1['y'] = np.where(bank1['y'].str.contains("yes"), 1, 0)
bank1

age  default  balance  housing  loan  day month  duration  campaign  \
0       58        0     2143        1     0    5   may       261         1   
1       44        0       29        1     0    5   may       151         1   
2       33        0        2        1     1    5   may        76         1   
3       47        0     1506        1     0    5   may        92         1   
4       33        0        1        0     0    5   may       198         1   
...    ...      ...      ...      ...   ...  ...   ...       ...       ...   
45206   51        0      825        0     0   17   nov       977         3   
45207   71        0     1729        0     0   17   nov       456         2   
45208   72        0     5715        0     0   17   nov      1127         5   
45209   57        0      668        0     0   17   nov       508         4   
45210   37        0     2971        0     0   17   nov       361         2   

       pdays  ...  education_secondary  education_tertiary  education_unknown  \
0         -1  ...                    0                   1                  0   
1         -1  ...                    1                   0                  0   
2         -1  ...                    1                   0                  0   
3         -1  ...                    0                   0                  1   
4         -1  ...                    0                   0                  1   
...      ...  ...                  ...                 ...                ...   
45206     -1  ...                    0                   1                  0   
45207     -1  ...                    0                   0                  0   
45208    184  ...                    1                   0                  0   
45209     -1  ...                    1                   0                  0   
45210    188  ...                    1                   0                  0   

       contact_cellular  contact_telephone  contact_unknown  poutcome_failure  \
0                     0                  0                1                 0   
1                     0                  0                1                 0   
2                     0                  0                1                 0   
3                     0                  0                1                 0   
4                     0                  0                1                 0   
...                 ...                ...              ...               ...   
45206                 1                  0                0                 0   
45207                 1                  0                0                 0   
45208                 1                  0                0                 0   
45209                 0                  1                0                 0   
45210                 1                  0                0                 0   

       poutcome_other  poutcome_success  poutcome_unknown  
0                   0                 0                 1  
1                   0                 0                 1  
2                   0                 0                 1  
3                   0                 0                 1  
4                   0                 0                 1  
...               ...               ...               ...  
45206               0                 0                 1  
45207               0                 0                 1  
45208               0                 1                 0  
45209               0                 0                 1  
45210               1                 0                 0  

[45211 rows x 38 columns]

In [44]:
order={'month':{'jan':1,'feb':2,'mar':3,'apr':4,'may':5,'jun':6,'jul':7,'aug':8,'sep':9,'oct':10,'nov':11,'dec':12}}

In [45]:
bank1=bank1.replace(order)
bank1

age  default  balance  housing  loan  day  month  duration  campaign  \
0       58        0     2143        1     0    5      5       261         1   
1       44        0       29        1     0    5      5       151         1   
2       33        0        2        1     1    5      5        76         1   
3       47        0     1506        1     0    5      5        92         1   
4       33        0        1        0     0    5      5       198         1   
...    ...      ...      ...      ...   ...  ...    ...       ...       ...   
45206   51        0      825        0     0   17     11       977         3   
45207   71        0     1729        0     0   17     11       456         2   
45208   72        0     5715        0     0   17     11      1127         5   
45209   57        0      668        0     0   17     11       508         4   
45210   37        0     2971        0     0   17     11       361         2   

       pdays  ...  education_secondary  education_tertiary  education_unknown  \
0         -1  ...                    0                   1                  0   
1         -1  ...                    1                   0                  0   
2         -1  ...                    1                   0                  0   
3         -1  ...                    0                   0                  1   
4         -1  ...                    0                   0                  1   
...      ...  ...                  ...                 ...                ...   
45206     -1  ...                    0                   1                  0   
45207     -1  ...                    0                   0                  0   
45208    184  ...                    1                   0                  0   
45209     -1  ...                    1                   0                  0   
45210    188  ...                    1                   0                  0   

       contact_cellular  contact_telephone  contact_unknown  poutcome_failure  \
0                     0                  0                1                 0   
1                     0                  0                1                 0   
2                     0                  0                1                 0   
3                     0                  0                1                 0   
4                     0                  0                1                 0   
...                 ...                ...              ...               ...   
45206                 1                  0                0                 0   
45207                 1                  0                0                 0   
45208                 1                  0                0                 0   
45209                 0                  1                0                 0   
45210                 1                  0                0                 0   

       poutcome_other  poutcome_success  poutcome_unknown  
0                   0                 0                 1  
1                   0                 0                 1  
2                   0                 0                 1  
3                   0                 0                 1  
4                   0                 0                 1  
...               ...               ...               ...  
45206               0                 0                 1  
45207               0                 0                 1  
45208               0                 1                 0  
45209               0                 0                 1  
45210               1                 0                 0  

[45211 rows x 38 columns]

In [46]:
bank1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  45211 non-null  int64
 1   default              45211 non-null  int32
 2   balance              45211 non-null  int64
 3   housing              45211 non-null  int32
 4   loan                 45211 non-null  int32
 5   day                  45211 non-null  int64
 6   month                45211 non-null  int64
 7   duration             45211 non-null  int64
 8   campaign             45211 non-null  int64
 9   pdays                45211 non-null  int64
 10  previous             45211 non-null  int64
 11  y                    45211 non-null  int32
 12  job_admin.           45211 non-null  uint8
 13  job_blue-collar      45211 non-null  uint8
 14  job_entrepreneur     45211 non-null  uint8
 15  job_housemaid        45211 non-null  uint8
 16  job_management       4

# ModelBuilding

In [55]:
features=pd.concat([bank1.iloc[:,0:11],bank1.iloc[:,12:]],axis=1)
target=bank1.iloc[:,11]

In [56]:
target

0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: y, Length: 45211, dtype: int32

In [66]:
import warnings
warnings.filterwarnings("ignore")

In [67]:
model=LogisticRegression()
model.fit(features,target)

LogisticRegression()

In [68]:
pred=model.predict(features)

In [69]:
pred

array([0, 0, 0, ..., 1, 0, 0])

# Evaluation

In [70]:
from sklearn.metrics import classification_report

In [71]:
print(classification_report(target,pred))

              precision    recall  f1-score   support

           0       0.90      0.98      0.94     39922
           1       0.61      0.22      0.32      5289

    accuracy                           0.89     45211
   macro avg       0.76      0.60      0.63     45211
weighted avg       0.87      0.89      0.87     45211



In [72]:
model.intercept_

array([-0.31548745])

In [65]:
model.coef_

array([[-1.64807923e-02, -2.11644843e-02,  1.98684704e-05,
        -8.25824213e-01, -2.29512748e-01, -1.90553086e-02,
        -3.50950372e-02,  3.71163263e-03, -2.91002997e-01,
         2.26293660e-03, -8.56667039e-02, -2.69522155e-02,
        -3.12257903e-01, -3.32086099e-02, -1.08532004e-02,
         1.93033308e-02,  1.97523883e-01, -1.75735700e-02,
        -1.08056312e-01,  4.64862580e-02, -7.33331528e-02,
         5.08121871e-04,  2.96871173e-03,  1.14881853e-02,
        -2.07095308e-01, -1.19837535e-01, -9.60521472e-02,
        -3.08977933e-01,  7.40621718e-02,  1.55232503e-02,
         1.60923581e-01,  6.31723114e-02, -5.39540551e-01,
        -1.69320141e-01, -4.03814246e-02,  4.00531263e-01,
        -5.06274356e-01]])

In [73]:
import statsmodels.api as sm
logit = sm.Logit(target, features)  
logit.fit().summary()

Optimization terminated successfully.
         Current function value: 0.249853
         Iterations 11


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      y   No. Observations:                45211
Model:                          Logit   Df Residuals:                    45178
Method:                           MLE   Df Model:                           32
Date:                Sun, 12 Mar 2023   Pseudo R-squ.:                  0.3076
Time:                        16:21:14   Log-Likelihood:                -11296.
converged:                       True   LL-Null:                       -16315.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=======================================================================================
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
age                     0.0017      0.002      0.801      0.423      -0.002       0.006
default                -0.1558      0.162     -0.964      0.335      -0.472       0.161
balance              1.854e-05   4.86e-06      3.812      0.000    9.01e-06    2.81e-05
housing                -0.7788      0.040    -19.608      0.000      -0.857      -0.701
loan                   -0.5603      0.058     -9.625      0.000      -0.674      -0.446
day                    -0.0042      0.002     -1.954      0.051      -0.008    1.17e-05
month                  -0.0185      0.007     -2.761      0.006      -0.032      -0.005
duration                0.0041   6.28e-05     64.591      0.000       0.004       0.004
campaign               -0.1061      0.010    -10.651      0.000      -0.126      -0.087
pdays                   0.0001      0.000      0.401      0.688      -0.000       0.001
previous                0.0102      0.007      1.561      0.118      -0.003       0.023
job_admin.              0.0435        nan        nan        nan         nan         nan
job_blue-collar        -0.3517        nan        nan        nan         nan         nan
job_entrepreneur       -0.4373        nan        nan        nan         nan         nan
job_housemaid          -0.4748        nan        nan        nan         nan         nan
job_management         -0.1781        nan        nan        nan         nan         nan
job_retired             0.3822        nan        nan        nan         nan         nan
job_self-employed      -0.3294        nan        nan        nan         nan         nan
job_services           -0.2698        nan        nan        nan         nan         nan
job_student             0.5482        nan        nan        nan         nan         nan
job_technician         -0.2224        nan        nan        nan         nan         nan
job_unemployed         -0.1914        nan        nan        nan         nan         nan
job_unknown            -0.2970        nan        nan        nan         nan         nan
marital_divorced       -0.5919        nan        nan        nan         nan         nan
marital_married        -0.7495        nan        nan        nan         nan         nan
marital_single         -0.4366        nan        nan        nan         nan         nan
education_primary      -0.6548        nan        nan        nan         nan         nan
education_secondary    -0.4883        nan        nan        nan         nan         nan
education_tertiary     -0.2507        nan        nan        nan         nan         nan
education_unknown      -0.3842        nan        nan        nan         nan         nan
contact_cellular       -0.1730   9.43e+05  -1.83e-07      1.000   -1.85e+06    1.85e+06
contact_telephone      -0.2577   8.72e+05  -2.96e-07      1.000   -1.71e+06    1.71e+06
contact_unknown        -1.3474   8.62e+05  -1.56e-06      1.000   -1.69e+06    1.69e+06
poutcome_failure       -1.0211        nan        nan        nan         n

In [77]:
y_pred=model.predict(features)
y_pred

array([0, 0, 0, ..., 1, 0, 0])

In [81]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(target,y_pred)
print (confusion_matrix) 

[[39195   727]
 [ 4151  1138]]


In [79]:
pd.crosstab(y_pred,target)

y          0     1
row_0             
0      39195  4151
1        727  1138